apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios-server
  template:
    metadata:
      labels:
        app: ms-usuarios-server
    spec:
      containers:
      - image: 4xe1/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios-server
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios-server
                  key: password
            - name: CURSOS_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: curso_url
